cosmologies: [0]
phases: [0]
seeds: [0]
hod_dir: /pscratch/sd/s/sbouchar/acm/bgs-21.35/parameters/hod_params
save_dir: /pscratch/sd/s/sbouchar/acm/bgs-21.35/measurements
estimator_config: estimator_parameters.yaml
n_hod: 100
sim_type: base
redshift: 0.2
add_rsd: true
add_ap: true
target_density: 1.20e-3
process_underdense: false
save_galaxies: false
measurements: ['tpcf', 'density_split', 'power_spectrum', 'density_split_power']
overwrite: false
log_level: INFO