# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Build documentation in the docs/ directory with Sphinx
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Python dependencies required to build the documentation
python:
  install:
    # Install only the documentation dependencies without building the package
    - requirements: docs/requirements.txt
