cosmologies: [0]
phases: [0]
seeds: [0]
hod_dir: /pscratch/sd/s/sbouchar/acm/bgs-v2.0/mr-20/parameters/hod_params
save_dir: /pscratch/sd/s/sbouchar/acm/bgs-v2.0/mr-20/measurements
estimator_config: estimator_parameters.yaml
n_hod: 100
sim_type: base
redshift: 0.2
add_rsd: true
add_ap: true
target_density: 8.5e-3
process_underdense: false
save_galaxies: false
measurements: ['spectrum', 'ds_xiqq', ds_xiqg]
overwrite: False
log_level: INFO