"""Tests generated by copilot, check by JM. Colley."""
import numpy as np
import pytest
import xarray as xr

from acm.utils.xarray import dataset_from_dict, dataset_to_dict, split_vars

# ruff: noqa: ANN001, ANN201, D102, S101

@pytest.fixture
def simple_dataset():
    """Create a dummy xarray dataset for testing."""
    return xr.Dataset(
        {
            "temp": xr.DataArray(
                np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]),
                dims=["x", "y"],
                attrs={"units": "K"},
            ),
            "pressure": xr.DataArray(
                np.array([[101.0, 102.0, 103.0], [104.0, 105.0, 106.0]]),
                dims=["x", "y"],
            ),
        },
        coords={"x": [0, 1], "y": [10, 20, 30]},
    )

@pytest.fixture
def simple_dict(simple_dataset):
    """Create a dummy dictionary representation of the simple dataset."""
    return dataset_to_dict(simple_dataset)

class TestDatasetToDict:
    """Tests for the dataset_to_dict function."""

    def test_keys_match_variables(self, simple_dataset, simple_dict):
        assert set(simple_dict.keys()) == set(simple_dataset.data_vars)

    def test_data_values_correct(self, simple_dataset, simple_dict):
        np.testing.assert_array_equal(simple_dict["temp"]["data"], simple_dataset["temp"].values)

    def test_dims_preserved(self, simple_dict):
        assert simple_dict["temp"]["dims"] == ("x", "y")

    def test_coords_preserved(self, simple_dict):
        assert "x" in simple_dict["temp"]["coords"]
        assert "y" in simple_dict["temp"]["coords"]
        np.testing.assert_array_equal(simple_dict["temp"]["coords"]["x"], [0, 1])
        np.testing.assert_array_equal(simple_dict["temp"]["coords"]["y"], [10, 20, 30])

    def test_attrs_preserved(self, simple_dict):
        assert simple_dict["temp"]["attrs"] == {"units": "K"}

    def test_empty_dataset_returns_empty_dict(self):
        assert dataset_to_dict(xr.Dataset()) == {}

    def test_simple_dataset(self, simple_dataset):
        """Test conversion of a simple dataset to dict."""
        result = dataset_to_dict(simple_dataset)
        expected_data = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
        assert "temp" in result
        assert "pressure" in result
        assert np.array_equal(result["temp"]["data"], expected_data)
        assert result["temp"]["dims"] == ("x", "y")

    def test_empty_dataset(self):
        """Test conversion of an empty dataset."""
        assert dataset_to_dict(xr.Dataset()) == {}


class TestDatasetFromDict:
    """Tests for the dataset_from_dict function."""

    def test_returns_dataset(self, simple_dict):
        assert isinstance(dataset_from_dict(simple_dict), xr.Dataset)

    def test_roundtrip(self, simple_dataset, simple_dict):
        """Converting to dict and back should recover the original dataset."""
        recovered = dataset_from_dict(simple_dict)
        xr.testing.assert_equal(recovered, simple_dataset)

    def test_empty_dict_returns_empty_dataset(self):
        assert len(dataset_from_dict({})) == 0

    def test_attributes_preserved(self, simple_dict):
        """Test that attributes are preserved during conversion."""
        ds = dataset_from_dict(simple_dict)
        assert ds["temp"].attrs == {"units": "K"}


class TestSplitVars:
    """Tests for the split_vars function."""

    @pytest.fixture
    def data_array(self):
        return xr.DataArray(
            np.arange(6.0),
            dims=["x"],
            coords={"x": [0, 1, 2, 3, 4, 5]},
        )

    def test_selected_values(self, data_array):
        (v_in, _), = split_vars(data_array, x=[1, 2])
        np.testing.assert_array_equal(v_in.values, [1.0, 2.0])

    def test_non_selected_values(self, data_array):
        (_, v_out), = split_vars(data_array, x=[1, 2])
        np.testing.assert_array_equal(v_out.values, [0.0, 3.0, 4.0, 5.0])

    def test_yields_one_tuple_per_variable(self, data_array):
        results = list(split_vars(data_array, data_array, x=[0]))
        assert len(results) == 2

    def test_select_all_leaves_empty_out(self, data_array):
        (_, v_out), = split_vars(data_array, x=[0, 1, 2, 3, 4, 5])
        assert v_out.size == 0

    def test_select_none_leaves_full_out(self, data_array):
        (v_in, v_out), = split_vars(data_array, x=[])
        assert v_in.size == 0
        np.testing.assert_array_equal(v_out.values, data_array.values)
