"""
tests generated by copilot, check by JM. Colley
"""

import pytest
import numpy as np
import xarray as xr
from acm.utils.xarray import dataset_to_dict, dataset_from_dict, split_vars


class TestDatasetToDict:
    def test_simple_dataset(self):
        """Test conversion of a simple dataset to dict."""
        ds = xr.Dataset(
            {
                "temp": (["x", "y"], np.array([[1, 2], [3, 4]])),
                "pressure": (["x", "y"], np.array([[5, 6], [7, 8]])),
            },
            coords={"x": [0, 1], "y": [0, 1]},
        )

        result = dataset_to_dict(ds)

        assert "temp" in result
        assert "pressure" in result
        assert np.array_equal(result["temp"]["data"], np.array([[1, 2], [3, 4]]))
        assert result["temp"]["dims"] == ("x", "y")

    def test_dataset_with_attributes(self):
        """Test conversion preserves attributes."""
        ds = xr.Dataset({"temp": (["x"], np.array([1, 2, 3]))})
        ds["temp"].attrs = {"units": "K", "long_name": "Temperature"}

        result = dataset_to_dict(ds)

        assert result["temp"]["attrs"] == {"units": "K", "long_name": "Temperature"}

    def test_empty_dataset(self):
        """Test conversion of an empty dataset."""
        ds = xr.Dataset()
        result = dataset_to_dict(ds)

        assert result == {}

    def test_dataset_coordinates(self):
        """Test that coordinates are properly extracted."""
        ds = xr.Dataset(
            {"var": (["x", "y"], np.array([[1, 2], [3, 4]]))},
            coords={"x": [10, 20], "y": [30, 40]},
        )

        result = dataset_to_dict(ds)

        assert "x" in result["var"]["coords"]
        assert "y" in result["var"]["coords"]
        assert np.array_equal(result["var"]["coords"]["x"], np.array([10, 20]))


class TestDatasetFromDict:
    def test_roundtrip_conversion(self):
        """Test converting dataset to dict and back."""
        ds_original = xr.Dataset(
            {"temp": (["x", "y"], np.array([[1, 2], [3, 4]]))},
            coords={"x": [0, 1], "y": [0, 1]},
        )

        data_dict = dataset_to_dict(ds_original)
        ds_reconstructed = dataset_from_dict(data_dict)

        assert "temp" in ds_reconstructed
        assert np.array_equal(
            ds_reconstructed["temp"].values, ds_original["temp"].values
        )

    def test_dataset_from_dict_with_attrs(self):
        """Test reconstruction with attributes."""
        data_dict = {
            "var": {
                "data": np.array([1, 2, 3]),
                "dims": ("x",),
                "coords": {"x": np.array([0, 1, 2])},
                "attrs": {"units": "K"},
                "name": "var",
            }
        }

        ds = dataset_from_dict(data_dict)

        assert ds["var"].attrs == {"units": "K"}


class TestSplitVars:
    def test_split_vars_basic(self):
        """Test basic splitting of variables."""
        data = xr.DataArray(
            np.arange(30).reshape(6, 5),
            coords={"x": range(6), "y": range(5)},
            dims=["x", "y"],
        )

        filter = {"x": [0, 1]}
        results = list(split_vars(data, **filter))

        assert len(results) == 1
        v_in, v_out = results[0]
        assert v_in.shape == (2, 5)
        assert v_out.shape == (4, 5)

    def test_split_vars_multiple(self):
        """Test splitting multiple variables."""
        data1 = xr.DataArray(np.arange(6).reshape(2, 3), dims=["x", "y"])
        data2 = xr.DataArray(np.arange(6, 12).reshape(2, 3), dims=["x", "y"])

        results = list(split_vars(data1, data2, x=0))

        assert len(results) == 2
