import logging
from pathlib import Path

import lsstypes
import matplotlib.pyplot as plt
import numpy as np

from acm.typing import LsstypeObject

from .base import BaseEstimator

logger = logging.getLogger(__name__)


class CountsInCells(BaseEstimator):
    """Class to compute counts in cells."""

    def compute(
        self,
        query_positions: np.ndarray | None = None,
        **kwargs,
    ) -> LsstypeObject:
        """
        Get the Counts in Cells (CIC) by querying the backend for the density contrast at specified positions.

        Parameters
        ----------
        query_positions: np.ndarray, optional
            Positions to query the density contrast, of shape (K, 3).
            If None, the query positions will be generated by the backend, unless when working with non-uniform geometry.
        **kwargs
                Additional keyword arguments for :meth:`~acm.estimators.galaxy_clustering.backends.base.EstimatorBackend.get_query_positions` method.
        """
        if query_positions is None and self.randoms_positions is None:
            raise ValueError(
                "query_positions must be provided when working with a non-uniform geometry."
            )
        if query_positions is None:
            query_positions = self.backend.get_query_positions(**kwargs)
        density_contrast = self.backend.read_density_contrast(
            query_positions, resampler="cic"
        )

        # TODO:: Find a clever way to bin the contrast histogram and save that instead.

        leaf = lsstypes.ObservableLeaf(
            density_contrast=density_contrast,
            index=np.arange(len(density_contrast)),
            coords=["index"],
        )
        return leaf

    @staticmethod
    def load(filename: str | Path, to_hist: bool = False, **kwargs) -> LsstypeObject:
        """
        Load a CountsInCells object from file.

        Parameters
        ----------
        filename: str | Path
            Path to the file containing the CountsInCells object.
        to_hist: bool, optional
            Whether to convert the loaded CountsInCells object to a histogram representation. Default is False.
        **kwargs
            Additional keyword arguments for the histogram conversion. See :func:`numpy.histogram` for details.

        Returns
        -------
        obj: lsstypes.ObservableLeaf
            The loaded CountsInCells object.
        """
        obj: lsstypes.ObservableLeaf = lsstypes.read(filename)
        if to_hist:
            # Convert the loaded object to a histogram representation
            hist, bin_edges = np.histogram(obj.density_contrast, **kwargs)
            hist_leaf = lsstypes.ObservableLeaf(
                hist=hist,
                bins=bin_edges[:-1],  # Use bin edges as indices
                coords=["bins"],
            )
            return hist_leaf
        return obj

    @staticmethod
    def plot(
        obj: LsstypeObject,
        fig: plt.Figure | None = None,
        ax: plt.Axes | None = None,
        **kwargs,
    ) -> tuple[plt.Figure, plt.Axes]:
        """
        Plot the Counts in Cells (CIC) from a :class:`~lsstypes.ObservableLeaf` object.

        Can either plot the histogram if the object has a 'hist' attribute, or plot a histogram of the density contrast if it does not.

        Parameters
        ----------
        obj: LsstypeObject
            The CountsInCells result to plot.
        fig: plt.Figure, optional
            The matplotlib figure to plot on. If None, a new figure will be created. Defaults to None.
        ax: plt.Axes, optional
            The matplotlib axes to plot on. If None, a new axes will be created. Defaults to None.
        **kwargs
            Additional keyword arguments for the plot. See :meth:`matplotlib.pyplot.bar` or :meth:`matplotlib.pyplot.hist` for details.
            Can also include 'figsize' to specify the size of the figure if new figure and axes are created.
            If 'fig' and 'ax' are provided, 'figsize' will be ignored.

        Returns
        -------
        fig, ax: tuple[plt.Figure, plt.Axes]
            The matplotlib figure and axes objects containing the plot.
        """
        figsize = kwargs.pop("figsize", (8, 6))
        if fig is None or ax is None:
            fig, ax = plt.subplots(figsize=figsize, **kwargs)
            ax.set_xlabel(r"$\Delta \left(R_s = 10\, h^{-1}{\rm Mpc}\right)$")
            ax.set_ylabel("PDF")

        if hasattr(obj, "hist"):
            # If the object has bins, plot a histogram using the provided bins
            ax.bar(obj.bins, obj.hist, width=np.diff(obj.bins)[0], align="edge", **kwargs)
        else:
            kwargs.setdefault("bins", 200)
            kwargs.setdefault("density", True)
            ax.hist(obj.density_contrast, **kwargs)
        return fig, ax
