import logging
import time
from pathlib import Path

import jax
import lsstypes
import matplotlib.pyplot as plt
import numpy as np
from jaxpower import (
    BinMesh2SpectrumPoles,
    ParticleField,
    compute_box2_normalization,
    compute_fkp2_shotnoise,
)
from jaxpower import compute_mesh2_spectrum as cm2s
from lsstypes.base import ObservableTree
from lsstypes.external import from_pycorr
from pandas import qcut
from pycorr import TwoPointCorrelationFunction

from acm.typing import LsstypeObject

from .backends.base import EstimatorBackend
from .backends.jaxpower import JaxpowerBackend
from .base import BaseEstimator

logger = logging.getLogger(__name__)

class DensitySplit(BaseEstimator):
    """Estimator for the Density Split Clustering. See http://arxiv.org/abs/2309.16541."""

    def __init__(
        self,
        backend: str | EstimatorBackend,
        data_positions: np.ndarray,
        randoms_positions: np.ndarray | None = None,
        data_weights: np.ndarray | None = None,
        randoms_weights: np.ndarray | None = None,
        query_positions: np.ndarray | None = None,
        nquantiles: int = 5,
        resampler: str = "cic",
        method: str = "randoms",
        nquery: int | None = None,
        **kwargs,
    ) -> None:
        """
        Initialize the Density Split estimator.

        Parameters
        ----------
        backend: str | EstimatorBackend
            The backend to use for the estimator.
        data_positions: np.ndarray
            Positions of data galaxies, of shape (N, 3).
        randoms_positions: np.ndarray, optional
            Positions of random catalog, of shape (M, 3).
        data_weights: np.ndarray, optional
            Weights for data galaxies, of shape (N,).
        randoms_weights: np.ndarray, optional
            Weights for randoms, of shape (M,).
        query_positions: np.ndarray, optional
            Positions to query the density contrast, of shape (K, 3).
            If None, the query positions will be generated by the backend, unless when working with non-uniform geometry.
        nquantiles: int, optional
            Number of quantiles to split the density contrast into. Defaults to 5.
        resampler: str, optional
            Resampling method to use for the density contrast.
            See :meth:`~acm.estimators.galaxy_clustering.backends.base.EstimatorBackend.read_density_contrast` for available options.
            Defaults to "cic".
        method: str, optional
            Method to use for the density contrast.
            See :meth:`~acm.estimators.galaxy_clustering.backends.base.EstimatorBackend.get_query_positions`.
            Defaults to "randoms".
        nquery: int, optional
            Number of query positions to use for the density contrast.
            See :meth:`~acm.estimators.galaxy_clustering.backends.base.EstimatorBackend.get_query_positions`.
        **kwargs
            Additional keyword arguments for the backend.
        """
        super().__init__(
            backend,
            data_positions,
            randoms_positions,
            data_weights,
            randoms_weights,
            **kwargs,
        )

        self._set_quantiles(
            query_positions=query_positions,
            nquantiles=nquantiles,
            resampler=resampler,
            method=method,
            nquery=nquery,
            # seed=42,
        )

        self.jit_cm2s = jax.jit(cm2s, static_argnames=["los"], donate_argnums=[0])

    def _set_quantiles(
        self,
        query_positions: np.ndarray | None = None,
        nquantiles: int = 5,
        resampler: str = "cic",
        **kwargs
    ) -> None:
        """
        Set the quantiles for the density split.

        Parameters
        ----------
        query_positions: np.ndarray, optional
            Positions to query the density contrast, of shape (K, 3).
            If None, the query positions will be generated by the backend, unless when working with non-uniform geometry.
        nquantiles: int, optional
            Number of quantiles to split the density contrast into. Defaults to 5.
        resampler: str, optional
            Resampling method to use for the density contrast.
            See :meth:`~acm.estimators.galaxy_clustering.backends.base.EstimatorBackend.read_density_contrast` for available options.
            Defaults to "cic".
        **kwargs
            Additional keyword arguments for :meth:`~acm.estimators.galaxy_clustering.backends.base.EstimatorBackend.get_query_positions` method.
        """
        t0 = time.time()
        if query_positions is None and self.randoms_positions is None:
            raise ValueError("query_positions must be provided when working with a non-uniform geometry.")
        query_positions = query_positions or self.backend.get_query_positions(**kwargs)
        density_contrast = self.backend.read_density_contrast(
            query_positions, resampler=resampler
        )

        quantiles_idx = qcut(density_contrast, nquantiles, labels=False)
        quantiles = [query_positions[quantiles_idx == i] for i in range(nquantiles)]
        logger.info(f"Quantiles calculated in {time.time() - t0:.2f} seconds.")

        # Set some privates attributes
        self._quantiles = quantiles
        self._quantiles_idx = quantiles_idx
        self._query_method = kwargs.get("method", "randoms")
        # NOTE: store delta query/density contrast ?

    @property
    def nquantiles(self) -> int:
        """Return the number of quantiles."""
        return len(self._quantiles)

    def _correlation(self, cross: bool, **kwargs) -> list[lsstypes.Count2Correlation]:
        """
        Compute the correlation function for each quantile.

        Parameters
        ----------
        cross: bool
            Whether to compute the cross-correlation (True) or auto-correlation (False).
        **kwargs
            Additional keyword arguments for :meth:`~pycorr.TwoPointCorrelationFunction`.

        Returns
        -------
        list[lsstypes.Count2Correlation]
            List of Count2Correlation objects for each quantile.
        """
        data_positions2 = self.data_positions if cross else None
        randoms_positions2 = self.randoms_positions if cross else None
        data_weights2 = self.data_weights if cross else None
        randoms_weights2 = self.randoms_weights if cross else None

        correlation_list = []
        R1R2 = None # Store common random pair counts to save time
        for quantile in self._quantiles:
            correlation = TwoPointCorrelationFunction(
                data_positions1=quantile,
                data_positions2=data_positions2,
                randoms_positions1=self.randoms_positions,
                randoms_positions2=randoms_positions2,
                data_weights1=None, # setting uniform default weights for quantiles
                data_weights2=data_weights2,
                randoms_weights1=None,
                randoms_weights2=randoms_weights2,
                position_type="pos", # Positions are of shape (N, 3)
                boxsize=self.backend.boxsize,
                R1R2=R1R2,
                **kwargs,
            )
            if kwargs.get("estimator") != "davispeebles":
                R1R2 = correlation.R1R2
            correlation_list.append(from_pycorr(correlation))
        return correlation_list

    # NOTE be careful, paint() default value changed as they are now passed as kwargs
    def _power(
        self,
        cross: bool,
        edges: np.ndarray | dict = {"step": 0.001},
        ells: tuple[int, ...] | list[int] = (0, 2, 4),
        los: str = "z",
        **kwargs
    ) -> list[lsstypes.Mesh2SpectrumPoles]:
        """
        Compute the power spectrum for each quantile.

        Parameters
        ----------
        cross: bool
            Whether to compute the cross-correlation (True) or auto-correlation (False).
        edges: np.ndarray | dict, optional
            The edges of the bins for the power spectrum. Can be provided as a numpy array or
            a dictionary. See :class:`~jaxpower.BinMesh2SpectrumPoles` for details. Defaults to {"step": 0.001}.
        ells: tuple[int, ...] | list[int], optional
            List of multipoles to compute.
            See :class:`~jaxpower.BinMesh2SpectrumPoles` for details.
            Defaults to (0, 2, 4).
        los: str, optional
            Line-of-sight direction for the power spectrum computation. Defaults to "z".
        **kwargs
            Additional keyword arguments when painting quantiles or data to meshes. See :class:`~jaxpower.ParticleField.paint` for details.

        Returns
        -------
        list[lsstypes.Mesh2SpectrumPoles]
            List of power spectrum objects for each quantile.
        """
        if not isinstance(self.backend, JaxpowerBackend):
            raise TypeError("The backend must be a JaxpowerBackend for power spectrum computation.")

        mattrs = self.backend.mattrs
        bin_mesh = BinMesh2SpectrumPoles(mattrs, edges, ells)

        # FIXME: handle survey-mode geometry with FKPField for data mesh
        # using randoms ? What about weights ? How to handle cross-correlation with randoms ?
        # FIXME: Use backend fields instead and paint on those!
        # FIXME: Compute shotnoise on cross too ?
        data_field = ParticleField(
            self.data_positions,  # ty:ignore[invalid-argument-type]
            attrs=mattrs,
            exchange=True,
            backend="jax",
        )
        data_mesh = data_field.paint(out='real', **kwargs)
        data_mesh = data_mesh - data_mesh.mean()

        spectrum_list = []
        for i, quantile in enumerate(self._quantiles):
            t0 = time.time()
            quantile_field = ParticleField(
                quantile,
                attrs=mattrs,
                exchange=True,
                backend="jax",
            )
            quantile_mesh = quantile_field.paint(out='real', **kwargs)
            quantile_mesh = quantile_mesh - quantile_mesh.mean()
            if cross:
                fields = (quantile_field, data_field)
                meshes = (quantile_mesh, data_mesh)
                num_shotnoise = None
            else:
                fields = (quantile_field,)
                meshes = (quantile_mesh,)
                num_shotnoise = compute_fkp2_shotnoise(quantile_field, bin=bin_mesh)

            norm = compute_box2_normalization(*fields, bin=bin_mesh)
            spectrum = self.jit_cm2s(*meshes, bin=bin_mesh, los=los)
            spectrum = spectrum.clone(norm=norm, num_shotnoise=num_shotnoise)

            spectrum_list.append(spectrum)
            logger.info(f"Q{i}-galaxy spectrum calculated in {time.time() - t0:.2f} s.")
        return spectrum_list

    def compute(
        self,
        cross: bool = True,
        data_type: str = "power",
        **kwargs,
    ) -> LsstypeObject:
        """
        Compute the density split clustering estimator.

        Parameters
        ----------
        cross: bool, optional
            Whether to compute the cross-correlation (True) or auto-correlation (False). Defaults to True.
        data_type: str, optional
            The type of estimator to compute (either "correlation" or "power"). Defaults to "power".
        **kwargs
            Additional keyword arguments for the estimator.
            See :meth:`~acm.estimators.galaxy_clustering.density_split.DensitySplit._correlation`
            and :meth:`~acm.estimators.galaxy_clustering.density_split.DensitySplit._power` for details.

        Returns
        -------
        LsstypeObject
            The computed estimator result, either as an ObservableTree of quantiles.
        """
        if data_type == "correlation":
            leaves = self._correlation(cross, **kwargs)
        elif data_type == "power":
            leaves = self._power(cross, **kwargs)
        else:
            raise ValueError(f"Unknown data type: {data_type}. Available types: 'correlation', 'power'.")

        quantiles = list(range(len(self._quantiles)))
        attrs = { # FIXME: Choose which attributes to keep !
            "query_method": self._query_method,
            "boxsize": self.backend.boxsize,
            "meshsize": self.backend.meshsize,
            "nquantiles": len(self._quantiles),
            "data_type": data_type,
        }
        tree = ObservableTree(leaves, quantiles=quantiles, attrs=attrs)
        return tree

    @staticmethod
    def load(filename: str | Path, project: bool = False, **kwargs) -> LsstypeObject:
        """
        Load a DensitySplit object from file.

        Parameters
        ----------
        filename: str | Path
            Path to the file containing the DensitySplit object.
        project: bool, optional
            Whether to project the loaded DensitySplit object onto specified multipoles. Default is False.
        **kwargs
            Additional keyword arguments for the projection. See :meth:`~lsstypes.Count2Correlation.project` for details.

        Returns
        -------
        obj: lsstypes.ObservableTree
            The loaded DensitySplit object, optionally projected onto the specified multipoles.
        """
        obj: LsstypeObject = lsstypes.read(filename)
        if project:
            leaves = [leaf.project(**kwargs) for leaf in obj.flatten(level=1)]
            obj = ObservableTree(leaves, quantiles=obj.quantiles, attrs=obj.attrs)
            # NOTE: assuming the estimator is a densitysplit result, we can call the quantiles attribute
        return obj

    @staticmethod
    def plot(
        obj: LsstypeObject,
        quantiles: list[int] = [0, 1, 3, 4],
        ell: int = 0,
        **kwargs
    ) -> tuple:
        """
        Plot the density split results.

        Parameters
        ----------
        obj: LsstypeObject
            The density split results to plot.
        quantiles: list[int], optional
            The quantiles to plot. Defaults to [0, 1, 3, 4].
        ell: int, optional
            The multipole to plot for each quantile. Defaults to 0.
        **kwargs
            Additional keyword arguments for the plot. See :meth:`matplotlib.pyplot.subplots` for details.
            Can also include 'fig' and 'ax' to provide existing figure and axes for plotting,
            or 'figsize' to specify the size of the figure if new figure and axes are created.
            If 'fig' and 'ax' are provided, 'figsize' will be ignored.

        Returns
        -------
        fig, ax: tuple
            The matplotlib figure and axes objects containing the plot.
        """
        data_type = obj.attrs.get("data_type")
        if data_type is None:
            raise ValueError("The provided object does not have a 'data_type' attribute. Cannot determine whether it is a correlation or power spectrum.")
        if data_type not in ["correlation", "power"]:
            raise ValueError(f"Unknown data type: {data_type}. Available types: 'correlation', 'power'.")
        is_power = data_type == "power"

        xlabel = r"$k$ [h/Mpc]" if is_power else r"$s$ [Mpc/h]"
        ylabel = r"$P(k)$ [(Mpc/h)$^3$]" if is_power else r"$s^2 \xi(s)$ [Mpc/h]$^2$"
        last_dim = "k" if is_power else "s"

        fig = kwargs.pop("fig", None)
        ax = kwargs.pop("ax", None)
        figsize = kwargs.pop("figsize", (8, 6))
        if fig is None or ax is None:
            fig, ax = plt.subplots(figsize=figsize, **kwargs)
            ax.set_xlabel(xlabel)
            ax.set_ylabel(ylabel)

        ld = obj.flatten(level=None)[0].coords(last_dim)
        for i, q in enumerate(quantiles):
            quantile = obj.get(quantiles=q)
            if is_power:
                pole = quantile.get(ells=ell).value()
            else:
                pole = quantile.project(ells=ell).value()
            ax.plot(ld, pole*ld**2, label=rf"${{\rm Q}}_{q}$", c=f'C{i}', **kwargs)
        return fig, ax

    # TODO: add back plot_quantiles
