import logging
import time
from pathlib import Path

import jax
import lsstypes
import matplotlib.pyplot as plt
import numpy as np
from jaxpower import (
    BinMesh2SpectrumPoles,
    ParticleField,
    compute_box2_normalization,
    compute_fkp2_shotnoise,
)
from jaxpower import compute_mesh2_spectrum as cm2s
from lsstypes.base import ObservableTree
from lsstypes.external import from_pycorr
from matplotlib.patches import Patch
from pandas import qcut
from pycorr import TwoPointCorrelationFunction

from acm.typing import LsstypeObject

from .backends.base import EstimatorBackend
from .backends.jaxpower import JaxpowerBackend
from .base import BaseEstimator

logger = logging.getLogger(__name__)


class DensitySplit(BaseEstimator):
    """Estimator for the Density Split Clustering. See http://arxiv.org/abs/2309.16541."""

    def __init__(
        self,
        backend: str | EstimatorBackend,
        data_positions: np.ndarray,
        randoms_positions: np.ndarray | None = None,
        data_weights: np.ndarray | None = None,
        randoms_weights: np.ndarray | None = None,
        query_positions: np.ndarray | None = None,
        nquantiles: int = 5,
        resampler: str = "cic",
        method: str = "randoms",
        nquery: int | None = None,
        **kwargs,
    ) -> None:
        """
        Initialize the Density Split estimator. Sets quantiles if the density contrast is already set in the backend, otherwise logs a message.

        Parameters
        ----------
        backend: str | EstimatorBackend
            The backend to use for the estimator.
        data_positions: np.ndarray
            Positions of data galaxies, of shape (N, 3).
        randoms_positions: np.ndarray, optional
            Positions of random catalog, of shape (M, 3).
        data_weights: np.ndarray, optional
            Weights for data galaxies, of shape (N,).
        randoms_weights: np.ndarray, optional
            Weights for randoms, of shape (M,).
        query_positions: np.ndarray, optional
            Positions to query the density contrast, of shape (K, 3).
            If None, the query positions will be generated by the backend, unless when working with non-uniform geometry.
        nquantiles: int, optional
            Number of quantiles to split the density contrast into. Defaults to 5.
        resampler: str, optional
            Resampling method to use for the density contrast.
            See :meth:`~acm.estimators.galaxy_clustering.backends.base.EstimatorBackend.read_density_contrast` for available options.
            Defaults to "cic".
        method: str, optional
            Method to use for the density contrast.
            See :meth:`~acm.estimators.galaxy_clustering.backends.base.EstimatorBackend.get_query_positions`.
            Defaults to "randoms".
        nquery: int, optional
            Number of query positions to use for the density contrast.
            See :meth:`~acm.estimators.galaxy_clustering.backends.base.EstimatorBackend.get_query_positions`.
        **kwargs
            Additional keyword arguments for the backend.
        """
        super().__init__(
            backend,
            data_positions,
            randoms_positions,
            data_weights,
            randoms_weights,
            **kwargs,
        )

        if self.backend._density_contrast is None:
            logger.info("Density contrast not set, cannot set quantiles yet.")
        else:
            self.set_quantiles(
                query_positions=query_positions,
                nquantiles=nquantiles,
                resampler=resampler,
                method=method,
                nquery=nquery,
                # seed=42,
            )

        self.jit_cm2s = jax.jit(cm2s, static_argnames=["los"], donate_argnums=[0])

    def set_quantiles(
        self,
        query_positions: np.ndarray | None = None,
        nquantiles: int = 5,
        resampler: str = "cic",
        **kwargs,
    ) -> None:
        """
        Set the quantiles for the density split. Requires the density contrast to be set in the backend.

        Parameters
        ----------
        query_positions: np.ndarray, optional
            Positions to query the density contrast, of shape (K, 3).
            If None, the query positions will be generated by the backend, unless when working with non-uniform geometry.
        nquantiles: int, optional
            Number of quantiles to split the density contrast into. Defaults to 5.
        resampler: str, optional
            Resampling method to use for the density contrast.
            See :meth:`~acm.estimators.galaxy_clustering.backends.base.EstimatorBackend.read_density_contrast` for available options.
            Defaults to "cic".
        **kwargs
            Additional keyword arguments for :meth:`~acm.estimators.galaxy_clustering.backends.base.EstimatorBackend.get_query_positions` method.
        """
        t0 = time.time()
        if query_positions is None and self.randoms_positions is None:
            raise ValueError(
                "query_positions must be provided when working with a non-uniform geometry."
            )
        if query_positions is None:
            query_positions = self.backend.get_query_positions(**kwargs)
        density_contrast = self.backend.read_density_contrast(
            query_positions, resampler=resampler
        )

        quantiles_idx = qcut(density_contrast, nquantiles, labels=False)
        quantiles = [query_positions[quantiles_idx == i] for i in range(nquantiles)]
        logger.info(f"Quantiles calculated in {time.time() - t0:.2f} seconds.")

        # Set some privates attributes
        self._quantiles = quantiles
        self._quantiles_idx = quantiles_idx
        self._query_method = kwargs.get("method", "randoms")
        # Should only be used for plotting the quantiles, not for any other purpose.
        self._density_contrast_query = density_contrast

    @property
    def nquantiles(self) -> int:
        """Return the number of quantiles."""
        if not hasattr(self, "_quantiles"):
            raise AttributeError("Quantiles have not been set yet.")
        return len(self._quantiles)

    def _correlation(self, cross: bool, **kwargs) -> list[lsstypes.Count2Correlation]:
        """
        Compute the correlation function for each quantile.

        Parameters
        ----------
        cross: bool
            Whether to compute the cross-correlation (True) or auto-correlation (False).
        **kwargs
            Additional keyword arguments for :meth:`~pycorr.TwoPointCorrelationFunction`.

        Returns
        -------
        list[lsstypes.Count2Correlation]
            List of Count2Correlation objects for each quantile.
        """
        data_positions2 = self.data_positions if cross else None
        randoms_positions2 = self.randoms_positions if cross else None
        data_weights2 = self.data_weights if cross else None
        randoms_weights2 = self.randoms_weights if cross else None

        correlation_list = []
        R1R2 = None  # Store common random pair counts to save time
        for quantile in self._quantiles:
            correlation = TwoPointCorrelationFunction(
                data_positions1=quantile,
                data_positions2=data_positions2,
                randoms_positions1=self.randoms_positions,
                randoms_positions2=randoms_positions2,
                data_weights1=None,  # setting uniform default weights for quantiles
                data_weights2=data_weights2,
                randoms_weights1=None,
                randoms_weights2=randoms_weights2,
                position_type="pos",  # Positions are of shape (N, 3)
                boxsize=self.backend.boxsize,
                R1R2=R1R2,
                **kwargs,
            )
            if kwargs.get("estimator") != "davispeebles":
                R1R2 = correlation.R1R2
            correlation_list.append(from_pycorr(correlation))
        return correlation_list

    # NOTE be careful, paint() default value changed as they are now passed as kwargs
    def _power(
        self,
        cross: bool,
        edges: np.ndarray | dict = {"step": 0.001},
        ells: tuple[int, ...] | list[int] = (0, 2, 4),
        los: str = "z",
        **kwargs,
    ) -> list[lsstypes.Mesh2SpectrumPoles]:
        """
        Compute the power spectrum for each quantile.

        Parameters
        ----------
        cross: bool
            Whether to compute the cross-correlation (True) or auto-correlation (False).
        edges: np.ndarray | dict, optional
            The edges of the bins for the power spectrum. Can be provided as a numpy array or
            a dictionary. See :class:`~jaxpower.BinMesh2SpectrumPoles` for details. Defaults to {"step": 0.001}.
        ells: tuple[int, ...] | list[int], optional
            List of multipoles to compute.
            See :class:`~jaxpower.BinMesh2SpectrumPoles` for details.
            Defaults to (0, 2, 4).
        los: str, optional
            Line-of-sight direction for the power spectrum computation. Defaults to "z".
        **kwargs
            Additional keyword arguments when painting quantiles or data to meshes. See :class:`~jaxpower.ParticleField.paint` for details.

        Returns
        -------
        list[lsstypes.Mesh2SpectrumPoles]
            List of power spectrum objects for each quantile.
        """
        if not isinstance(self.backend, JaxpowerBackend):
            raise TypeError(
                "The backend must be a JaxpowerBackend for power spectrum computation."
            )

        mattrs = self.backend.mattrs
        bin_mesh = BinMesh2SpectrumPoles(mattrs, edges, ells)

        # FIXME: handle survey-mode geometry with FKPField for data mesh
        # using randoms ? What about weights ? How to handle cross-correlation with randoms ?
        data_mesh = self.backend.data_field.paint(out="real", **kwargs)
        data_mesh = data_mesh - data_mesh.mean()

        spectrum_list = []
        for i, quantile in enumerate(self._quantiles):
            t0 = time.time()
            quantile_field = ParticleField(
                quantile,
                attrs=mattrs,
                exchange=True,
                backend="jax",
            )
            quantile_mesh = quantile_field.paint(out="real", **kwargs)
            quantile_mesh = quantile_mesh - quantile_mesh.mean()
            if cross:
                fields = (quantile_field, self.backend.data_field)
                meshes = (quantile_mesh, data_mesh)
                num_shotnoise = None
            else:
                fields = (quantile_field,)
                meshes = (quantile_mesh,)
                num_shotnoise = compute_fkp2_shotnoise(quantile_field, bin=bin_mesh)

            norm = compute_box2_normalization(*fields, bin=bin_mesh)
            spectrum = self.jit_cm2s(*meshes, bin=bin_mesh, los=los)
            spectrum = spectrum.clone(norm=norm, num_shotnoise=num_shotnoise)

            spectrum_list.append(spectrum)
            logger.info(f"Q{i}-galaxy spectrum calculated in {time.time() - t0:.2f} s.")
        return spectrum_list

    def compute(
        self,
        cross: bool = True,
        data_type: str = "power",
        **kwargs,
    ) -> LsstypeObject:
        """
        Compute the density split clustering estimator.

        Parameters
        ----------
        cross: bool, optional
            Whether to compute the cross-correlation (True) or auto-correlation (False). Defaults to True.
        data_type: str, optional
            The type of estimator to compute (either "correlation" or "power"). Defaults to "power".
        **kwargs
            Additional keyword arguments for the estimator.
            See :meth:`~acm.estimators.galaxy_clustering.density_split.DensitySplit._correlation`
            and :meth:`~acm.estimators.galaxy_clustering.density_split.DensitySplit._power` for details.

        Returns
        -------
        LsstypeObject
            The computed estimator result, either as an ObservableTree of quantiles.
        """
        nquantiles = self.nquantiles  # Will raise an error if quantiles are not set.
        if data_type == "correlation":
            leaves = self._correlation(cross, **kwargs)
        elif data_type == "power":
            leaves = self._power(cross, **kwargs)
        else:
            raise ValueError(
                f"Unknown data type: {data_type}. Available types: 'correlation', 'power'."
            )

        attrs = dict(
            name=self.__class__.__name__,
            data_type=data_type,
            cross=cross,
            query_method=self._query_method,
            boxsize=list(self.backend.boxsize),
            meshsize=list(self.backend.meshsize),
        )
        quantiles = list(range(nquantiles))
        tree = ObservableTree(leaves, quantiles=quantiles, attrs=attrs)
        return tree

    @staticmethod
    def load(filename: str | Path, project: bool = False, **kwargs) -> LsstypeObject:
        """
        Load a DensitySplit object from file.

        Parameters
        ----------
        filename: str | Path
            Path to the file containing the DensitySplit object.
        project: bool, optional
            Whether to project the loaded DensitySplit object onto specified multipoles. Default is False.
        **kwargs
            Additional keyword arguments for the projection. See :meth:`~lsstypes.Count2Correlation.project` for details.

        Returns
        -------
        obj: lsstypes.ObservableTree
            The loaded DensitySplit object, optionally projected onto the specified multipoles.
        """
        obj: LsstypeObject = lsstypes.read(filename)
        if project:
            leaves = [leaf.project(**kwargs) for leaf in obj.flatten(level=1)]
            obj = ObservableTree(leaves, quantiles=obj.quantiles, attrs=obj.attrs)
            # NOTE: assuming the estimator is a densitysplit result, we can call the quantiles attribute
        return obj

    @staticmethod
    def plot(
        obj: LsstypeObject,
        fig: plt.Figure | None = None,
        ax: plt.Axes | None = None,
        quantiles: list[int] = [0, 1, 3, 4],
        ell: int = 0,
        **kwargs,
    ) -> tuple[plt.Figure, plt.Axes]:
        """
        Plot the density split results.

        Parameters
        ----------
        obj: LsstypeObject
            The density split results to plot.
        fig: plt.Figure, optional
            The matplotlib figure to plot on. If None, a new figure will be created. Defaults to None.
        ax: plt.Axes, optional
            The matplotlib axes to plot on. If None, a new axes will be created. Defaults to None.
        quantiles: list[int], optional
            The quantiles to plot. Defaults to [0, 1, 3, 4].
        ell: int, optional
            The multipole to plot for each quantile. Defaults to 0.
        **kwargs
            Additional keyword arguments for the plot. See :meth:`matplotlib.pyplot.plot` for details.
            Can also include 'figsize' to specify the size of the figure if new figure and axes are created.

        Returns
        -------
        fig, ax: tuple[plt.Figure, plt.Axes]
            The matplotlib figure and axes objects containing the plot.
        """
        data_type = obj.attrs.get("data_type")
        if data_type is None:
            raise ValueError(
                "The provided object does not have a 'data_type' attribute. Cannot determine whether it is a correlation or power spectrum."
            )
        if data_type not in ["correlation", "power"]:
            raise ValueError(
                f"Unknown data type: {data_type}. Available types: 'correlation', 'power'."
            )
        is_power = data_type == "power"

        xlabel = r"$k$ [h/Mpc]" if is_power else r"$s$ [Mpc/h]"
        ylabel = r"$P(k)$ [(Mpc/h)$^3$]" if is_power else r"$s^2 \xi(s)$ [Mpc/h]$^2$"
        last_dim = "k" if is_power else "s"

        if fig is None or ax is None:
            fig, ax = plt.subplots(figsize=(8, 6))
            ax.set_xlabel(xlabel)
            ax.set_ylabel(ylabel)

        ld = obj.flatten(level=None)[0].coords(last_dim)
        for i, q in enumerate(quantiles):
            quantile = obj.get(quantiles=q)
            if is_power:
                pole = quantile.get(ells=ell).value()
            else:
                pole = quantile.project(ells=ell).value()
            ax.plot(ld, pole * ld**2, label=rf"${{\rm Q}}_{q}$", c=f"C{i}", **kwargs)
        return fig, ax

    @staticmethod
    def plot_quantiles(
        nquantiles: int,
        delta_query: np.ndarray,
        quantiles_idx: np.ndarray,
        fig: plt.Figure | None = None,
        ax: plt.Axes | None = None,
        colormap: str = "coolwarm",
        **kwargs,
    ) -> tuple[plt.Figure, plt.Axes]:
        """
        Plot the quantiles of the density contrast.

        Parameters
        ----------
        nquantiles: int
            The number of quantiles.
        delta_query: np.ndarray
            The density contrast query.
        quantiles_idx: np.ndarray
            The indices of the quantiles.
        fig: plt.Figure, optional
            The matplotlib figure to plot on. If None, a new figure will be created. Defaults to None.
        ax: plt.Axes, optional
            The matplotlib axes to plot on. If None, a new axes will be created. Defaults to None.
        colormap: str, optional
            The colormap to use for the plot. Defaults to "coolwarm".
        **kwargs
            Additional keyword arguments for the plot. See :meth:`matplotlib.pyplot.plot` for details.

        Returns
        -------
        fig, ax: tuple[plt.Figure, plt.Axes]
            The matplotlib figure and axes objects containing the plot.
        """
        cmap = plt.get_cmap(colormap)
        colors = cmap(np.linspace(0, 1, nquantiles))

        if fig is None or ax is None:
            fig, ax = plt.subplots(figsize=(4, 4))
            ax.set_xlabel(r"$\Delta \left(R_s \, h^{-1}{\rm Mpc}\right)$")
            ax.set_ylabel("PDF")

        _, bins, bar_container = ax.hist(
            delta_query,
            color="grey",
            **kwargs,
        )
        patches = getattr(bar_container, "patches", [])

        imin = 0
        handles = []
        for i in range(nquantiles):
            dmax = delta_query[quantiles_idx == i].max()
            imax = np.digitize(dmax, bins)[0] - 1
            for patch in patches[imin:imax]:
                patch.set_facecolor(colors[i])
            imin = imax
            handles.append(Patch(color=colors[i], label=rf"${{\rm Q}}_{i}$"))
        ax.legend(handlelength=1.0, handles=handles)
        return fig, ax
