name: Format, Typecheck & Test

on:
  pull_request:
    branches: ["dev","main"]
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  job_format:
    name : Ruff formatter
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.check_changes.outputs.has_changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.PUSH_KEY }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Configuration
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Installation package with editable mode
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Format
        id: format
        run: |
            ruff check --select I --fix acm
            ruff format --config quality/ruff.toml acm

      - name: Check if there are changes
        id: check_changes
        run: |
          if  [ -n "$(git status --porcelain)" ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected. Skipping tests and pushing changes."
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Push changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git add acm
          git commit -m "Ruff format"
          git push

  job-ty:
    name: Type checking with ty
    runs-on: ubuntu-latest
    needs: job_format
    # Formatting changes will trigger a new workflow run, so there is no need to run tests 
    if: needs.job_format.outputs.has_changes == 'false'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.PUSH_KEY }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Configuration
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Installation package with editable mode
        id: python-setup
        run: |
          echo "$(python --version)">> $GITHUB_OUTPUT
          python -m pip install --upgrade pip
          pip install ty

      - name: Type checking
        # First run is to get the number of errors without failing
        # Second run is to get the output in GitHub format for annotations
        run: |
          ty check acm --quiet --exit-zero --python-version 3.13
          ty check acm --python-version 3.13 --output-format github 
          echo "Exit code: $?"

  job_pytest:
    name : Pytest runner
    runs-on: ubuntu-latest
    needs: [job_format, job-ty]
    if: needs.job_format.outputs.has_changes == 'false'
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Configuration
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Cache installation
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip- 

      - name: mpi Installation
        run: |
          sudo apt install -y openmpi-bin libopenmpi-dev

      - name: Installation package with editable mode
        run: |
          python -m pip install --upgrade pip
          pip install -e .[testing,sunbird,cosmodesi,jaxpower]

      - name: Process tests
        run: |
          source quality/acm_quality_init.sh
          pytest tests/acm -vv -s
