name: CI for pull request format and pytest

on:
  pull_request:
    branches: ["dev","main"]
    types: [opened, synchronize, reopened]

  
jobs:
  job_format:
    name : ruff format
    runs-on: ubuntu-latest
    outputs:
       push_fmt: ${{ steps.format.outputs.push_fmt }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          persist-credentials: false
          
      - name: Configuration
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          
      - name: Cache installation
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip- 

      - name: Installation package with editable mode
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Format
        id: format
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_COMMIT }}
        run: |
          LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
          if echo "$LAST_COMMIT_MSG" | grep -q "ruff format"; then
            echo "Format already done"
            echo "push_fmt=false" >> $GITHUB_OUTPUT
          else
            echo "Try format"
            ruff check --select I --fix acm
            ruff format --config quality/ruff.toml acm
            if  [ -n "$(git status --porcelain)" ]; then
              git config --global user.name "Ruff formatter"
              git config --global user.email "formatter@ruff.org"
              git add acm
              git commit -m "ruff format"
              git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
              git push
              echo "push_fmt=true" >> $GITHUB_OUTPUT
            else
              echo "push_fmt=false" >> $GITHUB_OUTPUT
              echo "No formatting required."
            fi            
          fi

  job_pytest:
    name : pytest
    needs: job_format
    if: needs.job_format.outputs.push_fmt != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Cache installation
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip- 

      - name: mpi Installation
        run: |
          sudo apt install -y openmpi-bin libopenmpi-dev

      - name: Installation package with editable mode
        run: |
          python -m pip install --upgrade pip
          pip install -e .[testing,sunbird,cosmodesi,jaxpower]

      - name: Process tests
        run: |
          source quality/acm_quality_init.sh
          pytest tests/acm -vv -s          

# jobs:
#   job1:
#     name : Ruff format code and import
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout 
#         uses: actions/checkout@v4
#         with:
#           ref: ${{ github.event.pull_request.head.ref }}
#           persist-credentials: false

#       - name: Configuration
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.13"

#       - name: Install ruff
#         run: |
#           python -m pip install --upgrade pip
#           pip install ruff
          
#       - name: Format
#         env:
#           GITHUB_TOKEN: ${{ secrets.TOKEN_COMMIT }}
#         run: |
#           LAST_COMMIT_MSG=$(git log -1 --pretty=%B)

#           if echo "$LAST_COMMIT_MSG" | grep -q "Ruff format code and import"; then
#             echo "Skipping: already formatted commit"
#             exit 0
#           fi        
#           git status -v
#           ruff check --select I --fix acm
#           ruff format --config quality/ruff.toml acm
#           if [ -n "$(git status --porcelain)" ]; then
#             git config --global user.name "Ruff formatter"
#             git config --global user.email "formatter@ruff.org"
#             echo ${{ github.event.pull_request.head.ref }}
#             git add acm
#             git commit -a -m "Ruff format code and import"
#             git status -v
#             git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
#             git push -v origin ${{ github.event.pull_request.head.ref }}
#           else
#             echo "No modification."
#           fi

#   job2:
#     name : Run pytest
#     needs: job1 
#     runs-on: ubuntu-latest
#     outputs:
#           skip: ${{ steps.check.outputs.skip }}

#     steps:
#       - name: Check
#         run: |
#           echo "no pytest debug"
#           exit 0
#           LAST_COMMIT_MSG=$(git log -1 --pretty=%B)

#           if echo "$LAST_COMMIT_MSG" | grep -q "Ruff format code and import"; then
#             echo "Skipping: already formatted commit"
#             exit 0
#           fi        

#       - name: Cache installation
#         uses: actions/cache@v3
#         with:
#           path: ~/.cache/pip
#           key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
#           restore-keys: |
#             ${{ runner.os }}-pip- 

#       - name: mpi Installation
#         run: |
#           sudo apt install -y openmpi-bin libopenmpi-dev

#       - name: Installation package with editable mode
#         run: |
#           python -m pip install --upgrade pip
#           pip install -e .[testing,sunbird,cosmodesi,jaxpower]

#       - name: Process tests
#         run: |
#           source quality/acm_quality_init.sh
#           pytest tests/acm -vv -s